# Generated by Django 6.0 on 2025-12-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('offer', 'Offer')], db_index=True, default='applied', max_length=20),
        ),
    ]
