# Generated by Django 6.0 on 2025-12-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('recruiter', 'Recruiter')], default='user', max_length=20),
        ),
    ]
